FROM nvcr.io/nvidia/pytorch:26.04-py3
LABEL org.opencontainers.image.authors="Flavio.Calvo@unil.ch"

USER root

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Europe/Zurich

# Upgrade the packages in the container, install a few dependencies and fix the time zone
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y --no-install-recommends tzdata && \
	ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
	echo ${TZ} > /etc/timezone && \
	dpkg-reconfigure -f noninteractive tzdata && \
	apt-get install -y gdal-bin libgdal-dev && \
	rm -rf /var/lib/apt/lists/*

# Install `uv` directly in `/usr/bin`
RUN curl -LsSf https://astral.sh/uv/install.sh | env -i XDG_BIN_HOME=/usr/bin sh --noprofile --norc -l -s -- -q --no-modify-path

